export type ChromeLocale = 'en' | 'te'

export const CHROME = {
    en: {
        guideMe: 'Guide me',
        explorePlaces: 'Explore places',
        comingSoon: 'Coming soon',
        help: 'Help',
        home: 'Home',
        explore: 'Explore',
        searchPlaceholder: 'Search places…',
        heroEyebrow: 'Your local friend',
        heroTitle: 'Explore {city} like a local',
        heroQuestion: 'What would you like help with today?',
        attractions: 'Attractions',
        food: 'Food',
        hotels: 'Hotels',
        transport: 'Transport',
        emergency: 'Emergency',
        nearMe: 'Near me',
        openNow: 'Open now',
        familyFriendly: 'Family-friendly',
        freePlaces: 'Free places',
        popular: 'Popular in {city}',
        takeMyHand: "Take my hand — I'll walk you through, one place at a time.",
        viewAll: 'Explore places',
        langEnglish: 'English',
        langTelugu: 'తెలుగు',
        cityMenu: 'City',
    },
    te: {
        guideMe: 'నన్ను నడిపించు',
        explorePlaces: 'ప్రదేశాలు',
        comingSoon: 'త్వరలో',
        help: 'సహాయం',
        home: 'హోమ్',
        explore: 'చూడండి',
        searchPlaceholder: 'ప్రదేశాలను వెతకండి…',
        heroEyebrow: 'మీ స్థానిక స్నేహితుడు',
        heroTitle: '{city}ను స్థానికుడిలా చూడండి',
        heroQuestion: 'ఈరోజు దేనిలో సహాయం కావాలి?',
        attractions: 'చూడదగిన ప్రదేశాలు',
        food: 'ఆహారం',
        hotels: 'హోటళ్లు',
        transport: 'రవాణా',
        emergency: 'అత్యవసరం',
        nearMe: 'నాకు దగ్గర',
        openNow: 'ఇప్పుడు తెరిచి ఉన్నవి',
        familyFriendly: 'కుటుంబానికి అనుకూలం',
        freePlaces: 'ఉచిత ప్రవేశం',
        popular: '{city}లో ప్రసిద్ధం',
        takeMyHand: 'నా చెయ్యి పట్టుకోండి — ఒక్కో చోటుగా తీసుకెళ్తాను.',
        viewAll: 'ప్రదేశాలు చూడండి',
        langEnglish: 'English',
        langTelugu: 'తెలుగు',
        cityMenu: 'నగరం',
    },
} as const

export function fillCity(template: string, city: string) {
    return template.replace('{city}', city)
}
